name: Deploy React App to AWS

on:
  push:
    branches: [main]
 
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependency packages
        run: npm install
      - name: Build React App
        run: npm run build
      # Deploy to S3
